# Generated by Django 4.2.4 on 2023-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_module_temperature', models.SmallIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)])),
                ('module_status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3)),
                ('bypass_history', models.CharField(blank=True, max_length=500, null=True)),
                ('internal_temp', models.SmallIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('fan_status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3)),
            ],
        ),
    ]
